name:                piano-pal
version:             0.1.0.0
github:              "lfborjas/piano-pal"
license:             BSD3
author:              "Luis Borjas Reyes"
maintainer:          "luis@lfborjas.com"
copyright:           "2019 Luis Borjas Reyes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lfborjas/piano-pal#readme>

dependencies:
- base >= 4.7 && < 5
- Euterpea
- PortMidi # Euterpea dependency
- arrows # Euterpea dependency

library:
  source-dirs: src

executables:
  piano-pal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - piano-pal

tests:
  piano-pal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - piano-pal
